---
name: "gilot tracking schedule"
on:
  push:
    branches:
     - master
  schedule:
    - cron: "27 14 * * sun"
jobs:
  vimgilot:
    name: fetch vim/vim and process gilot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout vim/vim
        uses: actions/checkout@v2
        with:
          repository: vim/vim
          path: vim
          fetch-depth: 5000
      - name: Switch to master at vim
        run: |
          cd vim

          git remote set-head origin master
          git checkout master
          # git fetch --depth=5000 origin

          # echo check
          echo pwd $(pwd)
          git branch -va

          cd ..
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup pip and gilot
        run: |
          sudo pip3 install -U pip
          pip3 install git+https://github.com/hirokidaichi/gilot
      - name: Create gilot info and graph
        run: |
          mkdir build
          cp template/index.html build/
          gilot log --branch master --full vim/ > build/vim.csv
          gilot info          -i build/vim.csv  > build/vim.info.json
          gilot plot          -i build/vim.csv -o build/vim.plot.png
          gilot hotspot       -i build/vim.csv -o build/vim.hotspot.txt
          gilot hotgraph      -i build/vim.csv -o build/vim.hotgraph.png
          gilot author        -i build/vim.csv -o build/vim.author.png
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
